services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - ./Database/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: 
      context: ./Express-Backend
      args:
        - NODE_ENV=${NODE_ENV:-development}
    container_name: backend
    env_file:
      - ./Express-Backend/.env.${NODE_ENV:-development}
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./React-Frontend
      args:
        - VITE_ENV=${VITE_ENV:-development}
    container_name: frontend
    env_file:
      - ./React-Frontend/.env.${VITE_ENV:-development}
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
